### ISSUE TITLE
[Question] Multiline if-then-else

### ISSUE THREAD

**Issue by bulseeyeLF** [luarocks/luacheck#16]
Is there a way to enforce multi line syntax
```
if var then
  ...
else
  ...
end
```
rather than
```
if var then ... else ...
```
Tried going over the docs, couldn't find it

**Comment by hishamhm** [comment]
No, I don't think that feature exists.

>

**Comment by bulseeyeLF** [comment]
Closing with sadness

**Comment by alerque** [comment]
Luacheck is a linter, not a code format / style checker. As such only the lexical grammar matters, not the formatting style. Enforcing a code style rule would be out of scope for a linter. There are, however, Lua beautifier / pretty formatter scripts out there that take unformatted code and apply various style guides. My experience with them is that they tend to be too aggressive: in Lua more so than other languages I prefer to be able to pick styles situationally, but your millage may vary.
