### ISSUE TITLE
Release head version

### ISSUE THREAD

**Issue by ludrao** [luarocks/luacheck#17]
Might be useful to release the head version of  luacheck to luarocks
1) would fix the reported version
2) would add the few Lua 5.4 support fixes that were checked in last year.

I'd be glad to help but I suppose this would require the owner credentials.
(Note: I am not blocked I just installed the dev version, but to ease use for the masses it would be useful)

Thx for maintaining this tool!

**Comment by idbrii** [comment]
> 1. would fix the reported version

I guess that's where `luacheck --version` prints `Luacheck: 0.23.0` even though it was installed as 0.24.0-2? (fixed in 9e94be5c464473207434d7782ef31caa1fa073a2 but I think not tracked anywhere.)

**Comment by hishamhm** [comment]
Sorry for the late response!

I just pushed 0.25.0.

Luacheck is in need of new maintainers — I'm doing minimal administrative work around it, as time permits, until someone else comes up to take up the project (even if only to do this minimal administrative work more responsively than I'm able to).

> I'd be glad to help but I suppose this would require the owner credentials.

If you're still interested in helping out in any way, please reach out via hisham@luarocks.org and let's get something sorted! Thanks!
